backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "base_datos"
    label: "Gestión de Contenido"
    files:
      - label: "Todas las Brigadas"
        name: "brigadas"
        file: "brigadas.json"
        fields:
          - label: "Agrega tus actividades aquí"
            name: "lista_actividades"
            widget: "list"
            fields:
          - label: "Agrega tus actividades aquí"
            name: "lista_actividades"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Descripción", name: "description", widget: "text"}
              - {label: "Fotografía", name: "image", widget: "image", required: false}
              - {label: "Video (Opcional - Formato MP4)", name: "video", widget: "file", required: false}
